spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/bereketabInnowise/config-repo
#          uri: file://${user.home}/config-repo-local
          clone-on-start: true
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
server:
  port: 8888