apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server
  namespace: library
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-server
  template:
    metadata:
      labels:
        app: config-server
    spec:
      containers:
        - name: config-server
          image: bereketab24/library-config-server:latest
          ports:
            - containerPort: 8888
          env:
            - name: SPRING_CONFIG_LOCATION
              value: /config/application.yml
          volumeMounts:
            - name: config-volume
              mountPath: /config
      volumes:
        - name: config-volume
          configMap:
            name: config-server-config
---
apiVersion: v1
kind: Service
metadata:
  name: config-server
  namespace: library
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8888"
    prometheus.io/path: "/actuator/prometheus"
spec:
  ports:
    - port: 8888
      targetPort: 8888
  selector:
    app: config-server
