apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: library
type: Opaque
data:
  POSTGRES_USER: YmVyZWtldGFiMjQ=  # base64 for "bereketab24"
  POSTGRES_PASSWORD: YmVyZWtldGFiMjQ=  # base64 for "bereketab24"
