[versions]
spring-boot = "3.2.1"
spring-cloud = "2023.0.1"
spring-security = "6.2.0"
junit-jupiter = "5.9.3"
testcontainers = "1.19.0"
jjwt = "0.11.5"
postgresql = "42.6.0"
mongodb = "4.10.2"
resilience4j = "2.2.0"
liquibase = "4.24.0"

[libraries]
spring-boot-starter = { module = "org.springframework.boot:spring-boot-starter", version.ref = "spring-boot" }
spring-boot-starter-web = { module = "org.springframework.boot:spring-boot-starter-web", version.ref = "spring-boot" }
spring-boot-starter-test = { module = "org.springframework.boot:spring-boot-starter-test", version.ref = "spring-boot" }
spring-boot-starter-data-jpa = { module = "org.springframework.boot:spring-boot-starter-data-jpa", version.ref = "spring-boot" }
spring-boot-starter-security = { module = "org.springframework.boot:spring-boot-starter-security", version.ref = "spring-boot" }
spring-boot-starter-data-mongodb = { module = "org.springframework.boot:spring-boot-starter-data-mongodb", version.ref = "spring-boot" }

spring-cloud-dependencies = { module = "org.springframework.cloud:spring-cloud-dependencies", version.ref = "spring-cloud" }

spring-security-web = { module = "org.springframework.security:spring-security-web", version.ref = "spring-security" }
spring-boot-starter-webflux = { module = "org.springframework.boot:spring-boot-starter-webflux", version.ref = "spring-boot" }
#spring-security-webflux = { module = "org.springframework.security:spring-security-webflux", version.ref = "spring-security" }

spring-cloud-starter-config = { module = "org.springframework.cloud:spring-cloud-starter-config"}
spring-cloud-config-server = { module = "org.springframework.cloud:spring-cloud-config-server" }
spring-cloud-starter-gateway = { module = "org.springframework.cloud:spring-cloud-starter-gateway"}
spring-cloud-starter-consul-discovery = { module = "org.springframework.cloud:spring-cloud-starter-consul-discovery"}
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit-jupiter" }
testcontainers-postgresql = { module = "org.testcontainers:postgresql", version.ref = "testcontainers" }
testcontainers-junit-jupiter = { module = "org.testcontainers:junit-jupiter", version.ref = "testcontainers" }
jjwt-api = { module = "io.jsonwebtoken:jjwt-api", version.ref = "jjwt" }
jjwt-impl = { module = "io.jsonwebtoken:jjwt-impl", version.ref = "jjwt" }
jjwt-jackson = { module = "io.jsonwebtoken:jjwt-jackson", version.ref = "jjwt" }
postgresql = { module = "org.postgresql:postgresql", version.ref = "postgresql" }
mongodb-driver = { module = "org.mongodb:mongodb-driver-sync", version.ref = "mongodb" }
resilience4j-spring-boot3 = { module = "io.github.resilience4j:resilience4j-spring-boot3", version.ref = "resilience4j" }
liquibase = { module = "org.liquibase:liquibase-core", version.ref = "liquibase" }